#!/usr/bin/env bash
# get the information about a specific subdomain for our website.

print_domain_info() {
	record_type=$(dig "$2.$1" | grep -A1 ';; ANSWER SECTION:' | awk '{printf "%s", $4}')
	ip=$(dig "$2.$1" | grep -A1 ';; ANSWER SECTION:' | awk '{printf "%s", $5}')
	printf "The subdomain %s is a %s record and points to %s\n" "$2" "$record_type" "$ip"
}

if [ -z "$2" ]
then
	for sub in "www" "lb-01" "web-01" "web-02"
	do
		print_domain_info "$1" "$sub"
	done
else
	print_domain_info "$1" "$2"
fi
