#!/usr/bin/env bash
# script to discover if host are on the network using pingg
if ["$( echo -n "$1" | wc -m ) " == "0"];
then 
echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
exit 1
else
ping -c 5 "$1"
fi
