#!/usr/bin/env bash
# Init script that manages the 'manage_my_process' bash script.

FILE="/var/run/my_process.pid"
run_process="./manage_my_process"
operation=$1

case $operation in
	"start" )
		$run_process &
		pid=$!

		sudo touch $FILE
		sudo chmod 757 $FILE
		echo "$pid" > $FILE
		echo "manage_my_process started"
		;;
	"stop" )
		pkill -2 $run_process
		sudo rm -f $FILE
		echo "manage_my_process stopped"
		;;
	"restart" )
		pkill -2 $run_process
		sudo rm -f $FILE
		
		$run_process &
		pid=$!
		
		sudo touch $FILE
		sudo chmod 757 $FILE
		echo "$pid" > $FILE
		echo "manage_my_process restarted"
		;;
	* )
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
